### ISSUE TITLE
Heyo.

### ISSUE THREAD

**Issue by Dje95** [ammaraskar/pyCraft#104]
Getting this when trying to connect the bots.
> Server didn't respond back to handshake with proper packet!

Full: 

> Traceback (most recent call last):
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
AssertionError: Server didn't respond back to handshake with proper packet!
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
AssertionError: Server didn't respond back to handshake with proper packet!
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
AssertionError: Server didn't respond back to handshake with proper packet!
Connection to server failed
Traceback (most recent call last):
  File "Z:\pyCraft-bots\networking\NetworkManager.py", line 69, in run
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
Traceback (most recent call last):
  File "start.py", line 98, in <module>
    chat_input = raw_input()

**Comment by Dje95** [comment]
Forgot to mention. The server is running 1.8.8 spigot.

**Comment by joodicator** [comment]
The `bots` branch is from 2013 and does not support Minecraft 1.8.8. If you want to use its functionality, you'll have to implement it in the current version of pyCraft, i.e. on the `master` branch.

**Comment by joodicator** [comment]
I've added a notice about this to [`bots`](https://github.com/ammaraskar/pyCraft/tree/bots) so that others might be forewarned.
