### ISSUE TITLE
Would connecting using a minecraft account cause any trouble?

### ISSUE THREAD

**Issue by matcool** [ammaraskar/pyCraft#105]
This may sound really stupid but I was wondering if Mojang could "detect" it that you're logging in a weird way and maybe "ban" your account for doing so

**Comment by joodicator** [comment]
Trying to [https://wiki.vg/Authentication#Authenticate](`authenticate`) to a Mojang account too quickly can cause the account to be temporarily blocked. I've observed the blocking to last for several hours, maybe a day, in the past. If you're getting an `Invalid credentials` response, this could be the case for you, and the situation should be temporary.
