### ISSUE TITLE
How to catch ConnectionResetError ?

### ISSUE THREAD

**Issue by matcool** [ammaraskar/pyCraft#107]
I have tried putting `try: except Exception` everywhere in my code yet I still get this error when having trouble connecting to the server. My guess is that it's running on a different thread

**Comment by joodicator** [comment]
Yes, this exception is likely occurring in the networking thread. You can't prevent it from terminating the current connection, but you can handle the exception to perform actions including reconnecting, by setting the `handle_exception` argument of the [Connection](https://pycraft.readthedocs.io/en/latest/connecting.html#minecraft.networking.connection.Connection) constructor.
