### ISSUE TITLE
Send packets in plugins

### ISSUE THREAD

**Issue by roblabla** [ammaraskar/pyCraft#11]
Make it possible for plugins to send packets (through PacketSenderManager ?). This would make the plugin system way more useful. As far as I can see, it would only require the socket to be accessible by the plugins.
Also, maybe an overkill, but move chat printing and other game management stuff to plugins ?

**Comment by ammaraskar** [comment]
ayyy, I rewrote the whole project, you can now just do with the `Connection` class
```python
write_packet(self, packet, force=False)
```
https://github.com/ammaraskar/pyCraft/blob/master/network/connection.py#L52
