### ISSUE TITLE
about  create_AES_cipher

### ISSUE THREAD

**Issue by lightbrotherV** [ammaraskar/pyCraft#119]
I print the data from encryption.EncryptedFileObjectWrapper  in pyCraft.
shared_secret: \x33\xdb\x76\x2b\xa4\xd6\x79\x50\x74\x61\xd8\xef\x19\xdb\x89\x6f
secret_data: \xe7
origin_data: \x16

but I run this code：

def create_AES_cipher(shared_secret):
    cipher = Cipher(algorithms.AES(shared_secret), modes.CFB8(shared_secret),
                    backend=default_backend())
    return cipher
secret = b'\x33\xdb\x76\x2b\xa4\xd6\x79\x50\x74\x61\xd8\xef\x19\xdb\x89\x6f'
cipher = create_AES_cipher(secret)
encryptor = cipher.encryptor()
decryptor = cipher.decryptor()
res = decryptor.update(b"\xe7")
print(res)
------------------
res: \x95

the result is different from  the pyCraft.
Does  encryption.EncryptedFileObjectWrapper  have something special?

**Comment by ammaraskar** [comment]
Nope, nothing special. I think you're just misunderstanding how AES works
in cipher feedback mode. Each byte that gets encrypted affects the next
encrypted value. Therefore encrypting/decrypting two of the same bytes in
random order will not always result in the same thing.
