### ISSUE TITLE
[Enhancement for Docs] A Starter Tutorial

### ISSUE THREAD

**Issue by pinkpig3777** [ammaraskar/pyCraft#122]
Awesome project!

Now, it'd be even better if there were tutorials/guides for people just getting started programming stuff for Minecraft. Just basic & well explained tutorials of how to make your player move around, break blocks, etc. I know there's a docs folder but they don't seem very detailed on how to get started programming your own stuff. Also, intermediate/advanced tutorials would be neat as well.

Also, is there a specific way to open RST files to easily view them? Or just opening them in a text editor (like NotePad++)?

Thanks! :)

**Comment by joodicator** [comment]
I agree! The documentation for pyCraft is not currently in a good state, contrary to the development goal of "well documented" stated in the README. I'd like to contribute to improving it myself, when I get the time.

To answer your other question, the documentation can be compiled to HTML using [Sphinx](http://www.sphinx-doc.org/), e.g. using the provided Makefile.

**Comment by pinkpig3777** [comment]
Ah okay, thanks! And sounds good! :) 

Just to get an idea, any idea when you may have time? No worries if it'll be a while, I'm quite busy as well. :P

**Comment by joodicator** [comment]
@pinkpig3777 I'm afraid I cannot say at this time, but I think probably no later than June (2 months from now), at least.

**Comment by pinkpig3777** [comment]
Ok, no worries & thanks for info.
