### ISSUE TITLE
Pass additional arguments to the 'handler_func' of 'register_exception_handler'

### ISSUE THREAD

**Issue by mariolatiffathy** [ammaraskar/pyCraft#127]
Hi,

I am using `register_exception_handler` like that:

```python
def HandleThem(e, s):
    print(e)

connection.register_exception_handler(HandleThem)
```

so, this works fine! But I want to pass additional arguments to `HandleThem` so it should be like that:

```python
def HandleThem(e, s, onemoretext):
    print(e)
    print(onemoretext)

connection.register_exception_handler(HandleThem("and there are your exceptions"))
```

But this gives an error `TypeError: HandleThem() missing 2 required positional arguments: 'e' and 's'`

I don't know how to pass `e` and `s` and `onemoretext` together in the `register_exception_handler` call :/

**Comment by mariolatiffathy** [comment]
I found a solution if I don't want to print `e` ... and its like that:

```python
def HandleThem(*args):
    print(args[0])

connection.register_exception_handler(HandleThem("Hi"))
```
The result of this code will be `Hi` if an exception was thrown by PyCraft.

**Comment by ammaraskar** [comment]
The easiest way to do this is probably with functools's partial that lets you bind certain arguments to a function.

```python
from functools import partial

def HandleThem(onemoretext, e, s):
   print(e)
   print(onemoretext)

handleWithText = partial(HandleThem, "and there are your exceptions")
handleWithText(None, None) # testing it out
connection.register_exception_handler(handleWithText)
```

_(Note the flipped argument)_

**Comment by mariolatiffathy** [comment]
> The easiest way to do this is probably with functools's partial that lets you bind certain arguments to a function.
> 
> ```python
> from functools import partial
> 
> def HandleThem(onemoretext, e, s):
>    print(e)
>    print(onemoretext)
> 
> handleWithText = partial(HandleThem, "and there are your exceptions")
> handleWithText(None, None) # testing it out
> connection.register_exception_handler(handleWithText)
> ```
> 
> _(Note the flipped argument)_

Thanks a lot for the fast help :)
