### ISSUE TITLE
Unable to get Chat Message Packet Position

### ISSUE THREAD

**Issue by starcraft66** [ammaraskar/pyCraft#144]
ChatMessagePacket contains an `Enum` named `Position` indicating the type of message the server is sending to the client. I am trying to retrieve the name of the type of message in the enum based on the key the server sends but I am unable to use the enum in `ChatMessagePacket`.

My code looks something like
```
def handle_chat(self, chat_packet):
    self.es_logger.log_raw_message(type=chat_packet.Position(chat_packet.position).name, message=chat_packet.json_data)
```
That snippet of code produces the following error: `TypeError: Position() takes no arguments`.

If I re-implement the enum in my source code and call `Position(chat_packet.position).name`, it works as expected and returns something like `CHAT`, `SYSTEM` or `GAME_INFO`.

**Comment by ammaraskar** [comment]
Hey, the `Enum` there isn't the python3 Enum. pyCraft is py2/3 compatible so it has its own little Enum implementation here: https://github.com/ammaraskar/pyCraft/blob/6f2f25656c5c06fb4e5bd2be6fb1b0b2c2966ee5/minecraft/networking/types/enum.py#L19-L25

The correct way to do this would be: `chat_packet.Position.name_from_value(chat_packet.position)`

**Comment by starcraft66** [comment]
Thanks for the quick response, I totally overlooked the fact that pyCraft had its own implementation, I thought I was going crazy for a second!
