### ISSUE TITLE
Get the pyCraft Bot features to work for versions above 1.6.4

### ISSUE THREAD

**Issue by opd02** [ammaraskar/pyCraft#205]
Hello!

I see that the multiple bot feature of this repo was discontinued in MC version 1.6.4. I was wondering if anyone has already set it up for newer version of Minecraft. I am looking to have around 10 bots join my server and fly around/send and enchange some packets as a sort of stress test on my server.

**Comment by Mine215** [comment]
Do you mean 1.16.4? If so then im pretty sure pyCraft already supports it, just pull the new version down (`git pull`, I assume you know how to use that) and you should have it. If you are talking about 1.6.4, that is really old and I don't think anyone would have a real use for it around, in that case you should look to upgrade to at least 1.8.9. In case you really want 1.6.4 (not 1.16.4) you can look at how packets are made in pyCraft and try to implement the changes in the packets and protocol for the old version. If you are not talking about packets, then you are not being very clear by "features" of this repo.

**Comment by opd02** [comment]
> Do you mean 1.16.4? If so then im pretty sure pyCraft already supports it, just pull the new version down (`git pull`, I assume you know how to use that) and you should have it. If you are talking about 1.6.4, that is really old and I don't think anyone would have a real use for it around, in that case you should look to upgrade to at least 1.8.9. In case you really want 1.6.4 (not 1.16.4) you can look at how packets are made in pyCraft and try to implement the changes in the packets and protocol for the old version. If you are not talking about packets, then you are not being very clear by "features" of this repo.

I was mainly referring to the bot branch of this repo. It seems that "bot" branch of this project used to allow players to have bots join their server and fly around. This feature was left in 1.6.4 and not updated to 1.7 or higher. 

Basically, I am sorry I am being very unclear, long day. I am looking to have about 10 bots join my server and fly around. Is this something I can do with this repo? I emailed the creator and they said to make an issue and see if anyone has updated the "bots" section of the project.

**Comment by Mine215** [comment]
Well I highly suggest using the master branch. The master branch should be able to do what you want, only thing you have to do is add a couple movement packets. The bots branch shouldnt have anything the master branch doesnt have as its just an outdated version of the master branch with probably a couple changes made. No one has updated the bots section in 2 years (git shows you that if you look at it) and so it clearly isnt something you want to use if you want to use it in your up to date server. If you are willing to do some work you can 100% accomplish this so dont let the fact that the bots branch isnt what you want discourage you, research and look into how to add packets and try to add a few movement packets to use. One place you should look into using is [here](https://wiki.vg/Protocol) if you proceed with this project.

**Comment by opd02** [comment]
> Well I highly suggest using the master branch. The master branch should be able to do what you want, only thing you have to do is add a couple movement packets. The bots branch shouldnt have anything the master branch doesnt have as its just an outdated version of the master branch with probably a couple changes made. No one has updated the bots section in 2 years (git shows you that if you look at it) and so it clearly isnt something you want to use if you want to use it in your up to date server. If you are willing to do some work you can 100% accomplish this so dont let the fact that the bots branch isnt what you want discourage you, research and look into how to add packets and try to add a few movement packets to use. One place you should look into using is [here](https://wiki.vg/Protocol) if you proceed with this project.
> 
> 
> 
> (Also as a footnote I want to point out that pyCraft was never meant to be used for movement and such so it probably isnt going to be very easy to do that, you will have to figure out Minecraft physics and such too)

Thank you so much! Very very helpful. I'll keep you updated with what I end up coming up with. And you're right, probably best that I use the master branch.
