### ISSUE TITLE
How to change Minecraft Version?

### ISSUE THREAD

**Issue by jakehughes123** [ammaraskar/pyCraft#217]
How do I change the version of the game? 

I have been looking around and still can't find it :/

**Comment by jakehughes123** [comment]
```
from minecraft import authentication
from minecraft.exceptions import YggdrasilError
from minecraft.networking.connection import Connection
from minecraft.networking.packets import Packet, clientbound, serverbound

username = 'yumyum8463@gmail.com'
password = 'yumyum1234'
address = 'proxypipe.cosmicpvp.com'
port = 25565
auth_token = authentication.AuthenticationToken()
try:
    auth_token.authenticate(username, password)
except YggdrasilError as e:
    print(e)
    sys.exit()
print("Logged in as %s..." % auth_token.username)
connection = Connection(
    address, port, auth_token=auth_token)

while 1:
	msg = input('Enter command: ')
	if len(msg) > 0:
		packet = serverbound.play.ChatPacket()
		packet.message = msg
		connection.write_packet(packet)
```

**Comment by MisterSoandSo** [comment]
> In addition, some development snapshots and pre-release versions are supported: minecraft/__init__.py contains a full list of supported Minecraft versions and corresponding protocol version numbers.

Try taking a look at that file.

**Comment by joodicator** [comment]
@jakehughes123 pyCraft automatically uses the correct protocol version as determined by querying the server, but there is some control over this: see the `allowed_versions` and `initial_version` arguments to the `minecraft.networking.connection.Connection` constructor.
