### ISSUE TITLE
Why a copy of a DisconnectPacket doesn't work?

### ISSUE THREAD

**Issue by AlexandrMilko** [ammaraskar/pyCraft#222]
Hello. I have been trying to code a DisconnectPacket class refering to the protocol (https://wiki.vg/Protocol#Disconnect_.28play.29) to listen to it when my game client disconnects from a server.
It didn't work. Then I found an already made DisconnectPacket here https://github.com/ammaraskar/pyCraft/blob/2813d02ae7fb8182c3e5227a73de2240b09878d9/minecraft/networking/packets/clientbound/play/__init__.py#L123
And this one works(if I import it to my python file and use exactly it). I copied the code from it to my class and it doesn't hear it anyways.
So, I would like to know **why doesn't packet that i wrote work and the one that i found does** even if they have the same code? 
Thanks!

Here is the code for my DisconnectPacket class:
```
from minecraft.networking.packets import Packet

class MyDisconnectPacket(Packet):
    @staticmethod
    def get_id(context):
        return 0x19 if context.protocol_later_eq(741) else \
               0x1A if context.protocol_later_eq(721) else \
               0x1B if context.protocol_later_eq(550) else \
               0x1A if context.protocol_later_eq(471) else \
               0x1B if context.protocol_later_eq(345) else \
               0x1A if context.protocol_later_eq(332) else \
               0x1B if context.protocol_later_eq(318) else \
               0x1A if context.protocol_later_eq(107) else \
               0x40

    packet_name = "disconnect"

    definition = [
        {'json_data': String}]
```
And the function-listener in my Bot class:
```
@self.connection.listener(MyDisconnectPacket)    # self.connection = Connection(self.ip, self.port, username=self.USERNAME)
def handle_disconnect(disconnect_packet):
    print(disconnect_packet)
```

P.S. It listens to other packets, so probably it isn't the problem with my Bot class.

**Comment by joodicator** [comment]
`Connection` instances will not automatically use your packet, unless it is explicitly registered. I think that, currently, the best way to do this is to modify the function `minecraft.networking.packets.clientbound.play.get_packets` to return your custom `DisconnectPacket` class instead of the built-in one. If you don't want to modify that file, you could patch it like this:
```py
from minecraft.networking.packets import clientbound

def new_c_p_packets(context):
    packets = old_c_p_packets(context)
    packets.remove(clientbound.play.DisconnectPacket)
    packets.add(MyDisconnectPacket)
    return packets

old_c_p_packets, clientbound.play.get_packets = clientbound.play.get_packets, new_c_p_packets
```
It's kind of nasty to manipulate global variables like this, so I think this is part pyCraft's API that could be improved.

**Comment by AlexandrMilko** [comment]
Ok, thanks!
