### ISSUE TITLE
Authtoken Format

### ISSUE THREAD

**Issue by codeEpery** [ammaraskar/pyCraft#235]
Hey whats the format of the auth token which is used to check if the account is banned?
Is it a json format and what info is in it.

**Comment by joodicator** [comment]
@codeEpery According to https://wiki.vg/Authentication#Response, the access token is either a hexedecimal string or a _JSON Web Token_ (see https://jwt.io/). In my experience, it has always been the latter. I don't know so much myself about the data encoded within it - pyCraft treats it as an opaque string token. You might have better luck asking in `#mcdevs` on `irc.libera.chat`, if you want to dig deeper into this.
