### ISSUE TITLE
How to open a container?

### ISSUE THREAD

**Issue by NovaProtocol** [ammaraskar/pyCraft#243]
I made a entity interact packet as follow

```python
class InteractEntity(Packet):
        id = 0x0D
        packet_name = 'Interact Entity'
        definition = [
            {'entity_ID': VarInt},
            {'type': VarInt},
            {'target_x': Float},
            {'target_y': Float},
            {'target_z': Float},
            {'hand': VarInt},
            {'sneaking': Boolean},
        ]
```

and use the following code to use it.

```python
        packet = minecraft_packets.Serverbound.InteractEntity()
        packet.entity_ID = 54 # chests
        packet.type = 0
        packet.target_x = x
        packet.target_y = y
        packet.target_z = z
        packet.hand = 1
        packet.sneaking = False
        self.connection.write_packet(packet)
```
In theory, it should open the chests and not do anything with it but instead, it just leaves the game without doing anything. I'm testing this in vanilla 1.16.5 so in theory it should work but for some reason, it doesnt.

**Comment by MisterSoandSo** [comment]
Here a reference for [packet ids](https://github.com/MisterSoandSo/Minecraft-Packet-Protocol-Database).
I would suggest turning on debug mode to see what you get back from the server as a response .
