### ISSUE TITLE
How to reconnect to the server?

### ISSUE THREAD

**Issue by timof123** [ammaraskar/pyCraft#249]
When entering the server, there is a check for several seconds, after which the player is reconnected to another map. However, start.py doesn't reconnect, it doesn't write anything. How to perform this reconnection?

**Comment by MisterSoandSo** [comment]
You can do something like this  on start.py file.
```
disconnect_flag = False
def disconnect_function(disconnect_packet): 
  connection.disconnect()
  disconnect_flag = True
  print("Disconnected: " + disconnect_packet.json_data)
  time.sleep(300)
  connection.connect()
```

You trigger it by listening for:
`connection.register_packet_listener(disconnect_function, clientbound.play.DisconnectPacket)`
