### ISSUE TITLE
We need pyCraft3

### ISSUE THREAD

**Issue by zty012** [ammaraskar/pyCraft#258]
Emmmm

sorry english isn't my mother language

pyCraft is a great project. Butt, it is for python2!

We need a branch `python3`. It has awesome typing support. And remove some python2 features like `from __future__ import print_function`.

thanks xD

**Comment by Cassy-Lee** [comment]
It can run in python3 now, you may close this issue.

**Comment by zty012** [comment]
butt, there is no typing support
&nbsp;


shikukuya
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 下午3:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ammaraskar/pyCraft] We need pyCraft3 (Issue #258)





 
It can run in python3 now, you may close this issue.

**Comment by Cassy-Lee** [comment]
![图片](https://user-images.githubusercontent.com/104408348/233770100-a47f9926-7b88-4f20-810e-f552f8f698a7.png)
你瞎？

**Comment by zty012** [comment]
az，我说的是typing
&nbsp;


shikukuya
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月22日(星期六) 下午3:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ammaraskar/pyCraft] We need pyCraft3 (Issue #258)





 

 你瞎？

**Comment by Cassy-Lee** [comment]
不太理解你这个typing是什么意思，但是“pyCraft is a great project. Butt, it is for python2!”已经解决了，来把issue关掉
