### ISSUE TITLE
Rooted Roku

### ISSUE THREAD

**Issue by upintheairsheep** [ammaraskar/pyCraft#261]
Hello, I read your blog article about that rooted Roku, and wondering if it's still rooted or not. If it still has root, please give me outputs of the device tree, /proc/cpuinfo, /proc/meminfo/, /proc/partitions, /proc/mounts, and "ls / -R -a  -l". The reason for this is to have WAY more detailed internal documentation of the Roku's hardware and software, and if you have the binwalked image still, please upload that image to the Internet Archive, as then the community can see around the Roku's files and develop new Roku root programs.

Overall, I just want more documentation on the Roku's hardware. and the files of the Roku's software.

**Comment by MiniDigger** [comment]
how the heck did you end up on this repo?

**Comment by upintheairsheep** [comment]
It was the most popular one, I closed this to prevent clutter.

**Comment by upintheairsheep** [comment]
Never mind this is not ammar…

**Comment by ammaraskar** [comment]
Please email me instead of opening an issue on a random repo! See https://ammaraskar.com/ for my email.
