### ISSUE TITLE
Cannot run under Python 2.7, 32-bit Windows

### ISSUE THREAD

**Issue by madmaxoft** [ammaraskar/pyCraft#37]
I tried running `start.py` under Python 2.7 on 32-bit Windows 7, via Python Tools for Visual Studio 2010. I received the following error:
```
exceptions.ImportError occurred
Message: cannot import name __requires__
```
The exception report is generated in file `$/minecraft/__init__.py`, line 8 (end of file) The call stack is:
```
	_build_master in __init__ line 607
 	__init__ module line 3020
 	__init__ module line 7
 	encryption module line 3
 	connection module line 11
 	start module line 7
```

Versions:
- Windows 7 Pro, 64-bit
- Python 2.7 32-bit for Windows
- cffi 0.9.2
- cryptography 0.8.2
- enum34 1.0.4
- numpy 1.9.1
-.PIL 1.1.7
- pyasn1 0.1.7
- pycparser 2.10
-.requests 2.6
- six 1.9.0

Let me know if I can provide any more info.

**Comment by dkkline** [comment]
An actual traceback would be preferable. Could you try run it without Python Tools (via commandline python.exe)?

**Comment by madmaxoft** [comment]
I have Python 3.4 set as the default for commandline, I don't know how to switch to 2.7 (sorry, I'm a Python noob)

**Comment by madmaxoft** [comment]
I tried running it as `c:\path\to\pyCraft\> c:\python27\python start.py` and it seems to work just fine. Must be something specific about PTVS, then.
