### ISSUE TITLE
pyCraft bots doesnt work on 1.8

### ISSUE THREAD

**Issue by jaime29010** [ammaraskar/pyCraft#44]
Recently (just now) I've tried to run the bots on a server running spigot 1.8.3, and It doesnt work, as it havent been updated since 2 years I want to know if it will be updated or not. I really need it
I am using the command "start.py -x -f -b 5" and I get this error.
...
Connecting with 5 bots
Connection to server failed
Traceback (most recent call last):
  File "/home/jaime29010/Workspaces/pycraft/pyCraft-bots/networking/NetworkManager.py", line 69, in run
    assert packetid == "\xFD", "Server didn't respond back to handshake with proper packet!"
AssertionError: Server didn't respond back to handshake with proper packet!
(x5)
...

**Comment by joodicator** [comment]
Fixed in a753184ca24c8167743628c9106dc9207a6d7cc8.

See also my comment in issue #49.
