### ISSUE TITLE
Add a option to dont try to authenticate to mojang server (Offline)

### ISSUE THREAD

**Issue by jaime29010** [ammaraskar/pyCraft#45]
I've se en that the branch bots has a option to use offline mode, I would like to hace it un the master branch, so I only need to put a username and a address to connect to it

**Comment by Liberator9000** [comment]
i made offline version of this add me on skype
skype: live:carisma__cocuk

**Comment by ProFeeder** [comment]
Can you share it ?

**Comment by suBDavis** [comment]
Attempted a fix for this - #48

**Comment by joodicator** [comment]
This is fixed in 434bd1aab4897b954e3e62250e76690ff0329673. See my comment on pull request #48 for more details.
