### ISSUE TITLE
How to define new packets?

### ISSUE THREAD

**Issue by chibill** [ammaraskar/pyCraft#55]

**Comment by ammaraskar** [comment]
Good question, the documentation briefly glances over this but here's a more concrete example:

```python
from minecraft.networking.packets import Packet
from minecraft.networking.types import String, Long, Byte

class MyCustomPacket(Packet):
     id = 0xCAFEBABE
     packet_name = "my_custom_packet"

    definition = [
        {'my_string_field': String},
        {'my_long_field': Long},
        {'my_byte_field': Byte},
    ]
```

You can see all the types here https://github.com/ammaraskar/pyCraft/blob/master/minecraft/networking/types.py

and there are some more advanced examples of packets that handle different protocol versions here: https://github.com/ammaraskar/pyCraft/blob/master/minecraft/networking/packets.py#L746-L756

As far as actualy using the packet goes:
```python
def main():
    ...
    connection = Connection(options.address, options.port, username=options.username)
    connection.connect()

    custom_packet = MyCustomPacket()
    custom_packet.my_string_field = "Hello World"
    custom_packet.my_long_field   = 10000000
    custom_packet.my_byte_field   = 128
    connection.write_packet(custom_packet)

    connection.register_packet_listener(on_custom_packet, MyCustomPacket)

def on_custom_packet(packet):
    print packet.my_string_field, packet.my_long_field, packet.my_byte_field
```

Hope that helps, let me know if you have any questions.

**Comment by chibill** [comment]
Mostly I am tying to receive the ChunkData packets. So this is very helpful.

**Comment by chibill** [comment]
Also as a slight question how does PlayerListItemPacket work... I can't figure out how to get the information.

**Comment by joodicator** [comment]
@chibill A `PlayerListItemPacket` has two attributes: `action_type` (a `type`: a subclass of `PlayerListItemPacket.Action`) and `actions` (a `list` of actions of type `action_type`). The fields of each `Action` are listed in its `__slots__` and correspond to those specified [here](http://wiki.vg/Protocol#Player_List_Item).

However, you don't need to know about these internals, as a more convenient interface is implemented by `PlayerListItemPacket`, `PlayerListItemPacket.PlayerList`, and `PlayerListItemPacket.PlayerListItem`. To keep track of players, create an empty `PlayerList` first, then `apply` each `PlayerListItemPacket` received to the `PlayerList` to update it. For example, like [this](https://github.com/joodicator/mcchat2/blob/master/mcchat2.py#L803-L808).

Finally, access the contents of the list via the `players_by_uuid` attribute, a `dict` which maps UUID strings like `'{56643a92-2adf-4f5a-b816-60262ce4ce27}'` to `PlayerListItem` instances, each of which corresponds to a single player.

Perhaps these classes could be documented better and/or restructured to make this clearer.

**Comment by chibill** [comment]
Yeah. Thanks for the info. I think I am going to be moving to another lib that has more packets defined. (Has most of the packets done)

**Comment by chibill** [comment]
Thanks for the instructions. (I am trying to get the packet that holds the chunk data)

**Comment by joodicator** [comment]
Good luck.

**Comment by joodicator** [comment]
Oh, I didn't notice that you had edited your comment. The packets associated with chunk data are not implemented, but if you do end up implementing it yourself, it may be productive to incorporate your work into pyCraft - in which case, do submit a pull request.

**Comment by chibill** [comment]
I will do. (Mostly having trouble with trying to figure out how to decode http://wiki.vg/SMP_Map_Format ) which is used in chunk data packet. The amount of them can vary.

**Comment by ammaraskar** [comment]
Aah yes good point, for packets that need special reading instructions like that you can define them with the read method overridden like this:

```python
class WeirdlyParsedPacket(Packet):
    ...
   
    def read(self, file_object):
        length = VarInt.read(file_object)
        array = file_object.read(length)
        self.data_array = array
```

**Comment by chibill** [comment]
Now the only problem I have to deal with is wrapping my head around the stupidity of packing a bunch of blocks into one long... (Crazy Mojang...)

**Comment by ammaraskar** [comment]
As a side note this issue has raised some fairly good discussion that should ideally be incorporated in the documentation, the only current mention of implementing packets is the paragraph at the end here: https://pycraft.readthedocs.io/en/latest/connecting.html#writing-packets

I'm closing this issue since this seems to be resolved now.
