### ISSUE TITLE
Doesn't work in 1.5.*

### ISSUE THREAD

**Issue by 7020kjs** [ammaraskar/pyCraft#56]
Literally.

**Comment by rom1504** [comment]
Does it print "doesn't work" :) ?

**Comment by joodicator** [comment]
This is as intended: [the earliest supported version is 1.8](https://github.com/ammaraskar/pyCraft/blob/master/minecraft/__init__.py#L8-L45). However, you are welcome to contribute code adding support for earlier versions.
