### ISSUE TITLE
load_der_public_key

### ISSUE THREAD

**Issue by elrobtossohn** [ammaraskar/pyCraft#60]
```
Traceback (most recent call last):
  File "start.py", line 9, in <module>
    from minecraft.networking.connection import Connection
  File "/root/Stresstest/pyCraft-bots/pyCraft-master/minecraft/networking/connection.py", line 18, in <module>
    from . import encryption
  File "/root/Stresstest/pyCraft-bots/pyCraft-master/minecraft/networking/encryption.py", line 5, in <module>
    from cryptography.hazmat.primitives.serialization import load_der_public_key
ImportError: cannot import name load_der_public_key

```

What can i do?

**Comment by joodicator** [comment]
Might I ask what version of `cryptography` you have? You can check it with, e.g.:
```bash
python -c 'print(__import__("cryptography").__version__)'
```

**Comment by elrobtossohn** [comment]
0.6.1

**Comment by joodicator** [comment]
It seems that `load_der_private_key` was added in `cryptography` 0.8, so you will need at least that.

pyCraft's `requirements.txt` should be updated with the minimum required version of `cryptography` once that is determined, although it is of course a good idea to use the newest possible version of any security-related software. The current version of `cryptography` is 1.8.1, so I can't recommend using such an old version.

**Comment by elrobtossohn** [comment]
I update now with apt-get upgrade idk why it was an old version

**Comment by elrobtossohn** [comment]
If i wanna install it then come:

root@elrobtossohn:~/Stresstest/pyCraft-bots# pip install cryptography
Requirement already satisfied (use --upgrade to upgrade): cryptography in /usr/l                                                                                                                                                                                               ib/python2.7/dist-packages
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in                                                                                                                                                                                                run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundl                                                                                                                                                                                               e=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1293, in prepare_file                                                                                                                                                                                               s
    subreq = InstallRequirement(req, req_to_install)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 109, in __init__
    self.prereleases = any([is_prerelease(x[1]) and x[0] != "!=" for x in self.r                                                                                                                                                                                               eq.specs])
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 739, in is_prereleas                                                                                                                                                                                               e
    return any([any([y in set(["a", "b", "c", "rc", "dev"]) for y in x]) for x i                                                                                                                                                                                               n parsed])
TypeError: 'int' object is not iterable

Storing debug log for failure in /root/.pip/pip.log

**Comment by joodicator** [comment]
It looks like you have some other problems with `pip` and/or its dependencies. I suggest upgrading `pip` using your OS's package manager (or with `pip` itself, using `pip install --upgrade`) and then upgrading `cryptography`.

**Comment by joodicator** [comment]
I've set a minimum requirement for `cryptography` 1.5, as that is the earliest version I was able to compile on my system and hence properly test. See commit 19cdf80.

**Comment by elrobtossohn** [comment]
Who can i use the Bot?

**Comment by elrobtossohn** [comment]
How can i use the Bot?

**Comment by joodicator** [comment]
@elrobtossohn What bot do you mean?

**Comment by elrobtossohn** [comment]
I mean the Program complete

**Comment by elrobtossohn** [comment]
Also i wanna use more bots then 0

**Comment by joodicator** [comment]
@elrobtossohn pyCraft is a programming library, not a program in itself; but it does come with a sample program to illustrate its basic functionality. You can run it with:
```
./start.py
```
Or to see its command-line options:
```
./start.py --help
```
If you've gotten the idea that pyCraft includes a bot, you might be thinking of some other project that uses the pyCraft library.

**Comment by elrobtossohn** [comment]
I have read https://www.spigotmc.org/threads/stress-testing-servers.175/ and there it is so.

**Comment by elrobtossohn** [comment]
And i wanna do a Stress Test on my Server but i don't know how so i have found pyCraft

**Comment by joodicator** [comment]
I see. This was a variant of pyCraft written by Ammar quite a while ago. It's still present in the `bots` branch of this repository, but the code is very out of date, and pyCraft's API has changed since then, so it's not suitable for use with modern Minecraft servers.

It would not be hard, however, to write an updated version by comparing:
- https://github.com/ammaraskar/pyCraft/blob/bots/start.py (the old version, supporting multiple users)
- https://github.com/ammaraskar/pyCraft/blob/master/start.py (the new version, supporting only a single user)

In essence, you just have to do what the current `start.py` does multiple times in a loop, with a different username each time.

**Comment by elrobtossohn** [comment]
And how can be write an updated version?

**Comment by joodicator** [comment]
In my opinion, this is outside the scope of the pyCraft library, so I am not interested in rewriting it myself. You or somebody else will have to do it, perhaps creating a new project that depends on pyCraft.

**Comment by elrobtossohn** [comment]
Ok, But i don't know how to Rewrite it and i will do a Stress Test for my Server but i don't know how :(
