### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Camnooten** [ammaraskar/pyCraft#61]
When I run it it shows me this error:

**Comment by Camnooten** [comment]
**Acidenly pressed enter**
```
Traceback (most recent call last):
  File "C:\Users\camno\Desktop\pyCraft-bots\start.py", line 6, in <module>
    from networking import PacketSenderManager, NetworkManager
  File "C:\Users\camno\Desktop\pyCraft-bots\networking\NetworkManager.py", line 13, in <module>
    from Crypto.Random import _UserFriendlyRNG
ImportError: No module named Crypto.Random
```

**Comment by joodicator** [comment]
1. I believe you need to have [pycrypto](https://pypi.python.org/pypi/pycrypto) installed to run this version of pyCraft.
2. You appear to be using the `bots` branch, which is outdated with respect to pyCraft's current dependencies and compatibility. See [my comments on issue #60](https://github.com/ammaraskar/pyCraft/issues/60#issuecomment-302666766) for more on this.

**Comment by TiberiumN** [comment]
@Camnooten by the way - you can edit your posts on GitHub :)
