### ISSUE TITLE
When I tried to install it, it said the path can't be absolute

### ISSUE THREAD

**Issue by friedkeenan** [ammaraskar/pyCraft#63]
This specifically:
`ValueError: path '/usr/share/doc/pycraft' cannot be absolute`

**Comment by ammaraskar** [comment]
What's the full error and what command did you use to install the library?

**Comment by friedkeenan** [comment]
This is the log:
`Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Collecting pycraft
  1 location(s) to search for versions of pycraft:
  * https://pypi.python.org/simple/pycraft/
  Getting page https://pypi.python.org/simple/pycraft/
  Analyzing links from page https://pypi.python.org/simple/pycraft/
    Found link https://pypi.python.org/packages/0c/eb/d982dd3070e5f89c8ba78e642c6bdba2b80240df676e8956f42cebf3070b/PyCraft-1304090.tar.gz#md5=b930ebeef5663c783bad73f6e518c0c9 (from https://pypi.python.org/simple/pycraft/), version: 1304090
    Found link https://pypi.python.org/packages/11/8c/b6de8d6521bb3554babb624e0cdd6fc327dc9baf814b787ca291e468e8da/PyCraft-1403230.tar.bz2#md5=e82c45108c4d832f6a8d19b83231ce26 (from https://pypi.python.org/simple/pycraft/), version: 1403230
    Found link https://pypi.python.org/packages/1e/21/170965b1590b529c32880b91287558369ec98c34ddf518782b76bb8ac580/PyCraft-1411070.tar.bz2#md5=5320918b1031e56d4535e6845e63eeed (from https://pypi.python.org/simple/pycraft/), version: 1411070
    Found link https://pypi.python.org/packages/28/bb/6b8d840f831a92bfeecdabdb7df444a0bcd31fe5c151d9e9aa2222914c56/PyCraft-1402240.tar.bz2#md5=378f1dcb09f5c4869c2b454b59e13eb8 (from https://pypi.python.org/simple/pycraft/), version: 1402240
    Found link https://pypi.python.org/packages/61/51/b899504743f4883079e0bd41555da301e3975e8aad2e203f04a9502186dd/PyCraft-1304090.tar.bz2#md5=9ceceaec047970591fd07d5571517347 (from https://pypi.python.org/simple/pycraft/), version: 1304090
    Found link https://pypi.python.org/packages/65/40/58580b5a9c34cbd4444b83dbaa1f87b03c2e95151641ff1889967aa8d355/PyCraft-1403100.tar.bz2#md5=4a0be296cb3dbd5ff9cbcdfe1fd8365e (from https://pypi.python.org/simple/pycraft/), version: 1403100
    Found link https://pypi.python.org/packages/70/7d/ebad9f0ed61b2120edbcbbb7baa48b5399cb306ded7e82ab77e5280d8c05/PyCraft-1503040.tar.bz2#md5=422ede78f942a15c20bbcdfa0e1e62c6 (from https://pypi.python.org/simple/pycraft/), version: 1503040
    Found link https://pypi.python.org/packages/ac/e6/ade236af7a5b7619453348c1d8891e99926927c0a507a9f31d1fe0901929/PyCraft-1405030.tar.bz2#md5=b525737fce4433046ab7f2e2385a3956 (from https://pypi.python.org/simple/pycraft/), version: 1405030
    Found link https://pypi.python.org/packages/ce/9d/7178e9eb7cb00f22219fc454d86cab4c61c6efd3dd783d5b0583d3c5c1c9/PyCraft-1403020.tar.bz2#md5=9cedc4528b658b63f71ad30dc5de343b (from https://pypi.python.org/simple/pycraft/), version: 1403020
  Using version 1503040 (newest of versions: 1304090, 1402240, 1403020, 1403100, 1403230, 1405030, 1411070, 1503040)
  Using cached PyCraft-1503040.tar.bz2
  Downloading from URL https://pypi.python.org/packages/70/7d/ebad9f0ed61b2120edbcbbb7baa48b5399cb306ded7e82ab77e5280d8c05/PyCraft-1503040.tar.bz2#md5=422ede78f942a15c20bbcdfa0e1e62c6 (from https://pypi.python.org/simple/pycraft/)
  Running setup.py (path:C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\setup.py) egg_info for package pycraft
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info\PyCraft.egg-info
    writing dependency_links to pip-egg-info\PyCraft.egg-info\dependency_links.txt
    writing pip-egg-info\PyCraft.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\PyCraft.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\PyCraft.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\PyCraft.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\PyCraft.egg-info\SOURCES.txt'
  Source in c:\users\name\appdata\local\temp\pip-build-3xq5otjv\pycraft has version 1503040, which satisfies requirement pycraft from https://pypi.python.org/packages/70/7d/ebad9f0ed61b2120edbcbbb7baa48b5399cb306ded7e82ab77e5280d8c05/PyCraft-1503040.tar.bz2#md5=422ede78f942a15c20bbcdfa0e1e62c6
Installing collected packages: pycraft
    Running command c:\users\name\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\name\\AppData\\Local\\Temp\\pip-build-3xq5otjv\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\name\AppData\Local\Temp\pip-5t4wukmu-record\install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\pycraft
    copying Src\anvil.py -> build\lib\pycraft
    copying Src\geometry.py -> build\lib\pycraft
    copying Src\low.py -> build\lib\pycraft
    copying Src\nbt.py -> build\lib\pycraft
    copying Src\__init__.py -> build\lib\pycraft
    running install_lib
    running install_data
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\setup.py", line 42, in <module>
        keywords = ["Minecraft"],
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\command\install.py", line 551, in run
        self.run_command(cmd_name)
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\command\install_data.py", line 56, in run
        dir = convert_path(f[0])
      File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/usr/share/doc/pycraft' cannot be absolute
Cleaning up...
  Removing source in C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft
Command "c:\users\name\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\name\\AppData\\Local\\Temp\\pip-build-3xq5otjv\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\name\AppData\Local\Temp\pip-5t4wukmu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\
Exception information:
Traceback (most recent call last):
  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "c:\users\name\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\name\\AppData\\Local\\Temp\\pip-build-3xq5otjv\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\name\AppData\Local\Temp\pip-5t4wukmu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\
`
I used `pip install pyCraft`

**Comment by friedkeenan** [comment]
Here's the log:

	Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
	Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
	Collecting pycraft
	  1 location(s) to search for versions of pycraft:
	  * https://pypi.python.org/simple/pycraft/
	  Getting page https://pypi.python.org/simple/pycraft/
	  Analyzing links from page https://pypi.python.org/simple/pycraft/
		Found link https://pypi.python.org/packages/0c/eb/d982dd3070e5f89c8ba78e642c6bdba2b80240df676e8956f42cebf3070b/PyCraft-1304090.tar.gz#md5=b930ebeef5663c783bad73f6e518c0c9 (from https://pypi.python.org/simple/pycraft/), version: 1304090
		Found link https://pypi.python.org/packages/11/8c/b6de8d6521bb3554babb624e0cdd6fc327dc9baf814b787ca291e468e8da/PyCraft-1403230.tar.bz2#md5=e82c45108c4d832f6a8d19b83231ce26 (from https://pypi.python.org/simple/pycraft/), version: 1403230
		Found link https://pypi.python.org/packages/1e/21/170965b1590b529c32880b91287558369ec98c34ddf518782b76bb8ac580/PyCraft-1411070.tar.bz2#md5=5320918b1031e56d4535e6845e63eeed (from https://pypi.python.org/simple/pycraft/), version: 1411070
		Found link https://pypi.python.org/packages/28/bb/6b8d840f831a92bfeecdabdb7df444a0bcd31fe5c151d9e9aa2222914c56/PyCraft-1402240.tar.bz2#md5=378f1dcb09f5c4869c2b454b59e13eb8 (from https://pypi.python.org/simple/pycraft/), version: 1402240
		Found link https://pypi.python.org/packages/61/51/b899504743f4883079e0bd41555da301e3975e8aad2e203f04a9502186dd/PyCraft-1304090.tar.bz2#md5=9ceceaec047970591fd07d5571517347 (from https://pypi.python.org/simple/pycraft/), version: 1304090
		Found link https://pypi.python.org/packages/65/40/58580b5a9c34cbd4444b83dbaa1f87b03c2e95151641ff1889967aa8d355/PyCraft-1403100.tar.bz2#md5=4a0be296cb3dbd5ff9cbcdfe1fd8365e (from https://pypi.python.org/simple/pycraft/), version: 1403100
		Found link https://pypi.python.org/packages/70/7d/ebad9f0ed61b2120edbcbbb7baa48b5399cb306ded7e82ab77e5280d8c05/PyCraft-1503040.tar.bz2#md5=422ede78f942a15c20bbcdfa0e1e62c6 (from https://pypi.python.org/simple/pycraft/), version: 1503040
		Found link https://pypi.python.org/packages/ac/e6/ade236af7a5b7619453348c1d8891e99926927c0a507a9f31d1fe0901929/PyCraft-1405030.tar.bz2#md5=b525737fce4433046ab7f2e2385a3956 (from https://pypi.python.org/simple/pycraft/), version: 1405030
		Found link https://pypi.python.org/packages/ce/9d/7178e9eb7cb00f22219fc454d86cab4c61c6efd3dd783d5b0583d3c5c1c9/PyCraft-1403020.tar.bz2#md5=9cedc4528b658b63f71ad30dc5de343b (from https://pypi.python.org/simple/pycraft/), version: 1403020
	  Using version 1503040 (newest of versions: 1304090, 1402240, 1403020, 1403100, 1403230, 1405030, 1411070, 1503040)
	  Using cached PyCraft-1503040.tar.bz2
	  Downloading from URL https://pypi.python.org/packages/70/7d/ebad9f0ed61b2120edbcbbb7baa48b5399cb306ded7e82ab77e5280d8c05/PyCraft-1503040.tar.bz2#md5=422ede78f942a15c20bbcdfa0e1e62c6 (from https://pypi.python.org/simple/pycraft/)
	  Running setup.py (path:C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\setup.py) egg_info for package pycraft
		Running command python setup.py egg_info
		running egg_info
		creating pip-egg-info\PyCraft.egg-info
		writing dependency_links to pip-egg-info\PyCraft.egg-info\dependency_links.txt
		writing pip-egg-info\PyCraft.egg-info\PKG-INFO
		writing top-level names to pip-egg-info\PyCraft.egg-info\top_level.txt
		writing manifest file 'pip-egg-info\PyCraft.egg-info\SOURCES.txt'
		warning: manifest_maker: standard file '-c' not found

		reading manifest file 'pip-egg-info\PyCraft.egg-info\SOURCES.txt'
		writing manifest file 'pip-egg-info\PyCraft.egg-info\SOURCES.txt'
	  Source in c:\users\name\appdata\local\temp\pip-build-3xq5otjv\pycraft has version 1503040, which satisfies requirement pycraft from https://pypi.python.org/packages/70/7d/ebad9f0ed61b2120edbcbbb7baa48b5399cb306ded7e82ab77e5280d8c05/PyCraft-1503040.tar.bz2#md5=422ede78f942a15c20bbcdfa0e1e62c6
	Installing collected packages: pycraft
		Running command c:\users\name\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\name\\AppData\\Local\\Temp\\pip-build-3xq5otjv\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\name\AppData\Local\Temp\pip-5t4wukmu-record\install-record.txt --single-version-externally-managed --compile
		running install
		running build
		running build_py
		creating build
		creating build\lib
		creating build\lib\pycraft
		copying Src\anvil.py -> build\lib\pycraft
		copying Src\geometry.py -> build\lib\pycraft
		copying Src\low.py -> build\lib\pycraft
		copying Src\nbt.py -> build\lib\pycraft
		copying Src\__init__.py -> build\lib\pycraft
		running install_lib
		running install_data
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\setup.py", line 42, in <module>
			keywords = ["Minecraft"],
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\core.py", line 148, in setup
			dist.run_commands()
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 955, in run_commands
			self.run_command(cmd)
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
			cmd_obj.run()
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\setuptools\command\install.py", line 61, in run
			return orig.install.run(self)
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\command\install.py", line 551, in run
			self.run_command(cmd_name)
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\cmd.py", line 313, in run_command
			self.distribution.run_command(command)
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\dist.py", line 974, in run_command
			cmd_obj.run()
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\command\install_data.py", line 56, in run
			dir = convert_path(f[0])
		  File "c:\users\name\appdata\local\programs\python\python35-32\lib\distutils\util.py", line 125, in convert_path
			raise ValueError("path '%s' cannot be absolute" % pathname)
		ValueError: path '/usr/share/doc/pycraft' cannot be absolute
	Cleaning up...
	  Removing source in C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft
	Command "c:\users\name\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\name\\AppData\\Local\\Temp\\pip-build-3xq5otjv\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\name\AppData\Local\Temp\pip-5t4wukmu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\
	Exception information:
	Traceback (most recent call last):
	  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\basecommand.py", line 215, in main
		status = self.run(options, args)
	  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\commands\install.py", line 342, in run
		prefix=options.prefix_path,
	  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\req\req_set.py", line 784, in install
		**kwargs
	  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\req\req_install.py", line 878, in install
		spinner=spinner,
	  File "c:\users\name\appdata\local\programs\python\python35-32\lib\site-packages\pip\utils\__init__.py", line 707, in call_subprocess
		% (command_desc, proc.returncode, cwd))
	pip.exceptions.InstallationError: Command "c:\users\name\appdata\local\programs\python\python35-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\name\\AppData\\Local\\Temp\\pip-build-3xq5otjv\\pycraft\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\name\AppData\Local\Temp\pip-5t4wukmu-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\name\AppData\Local\Temp\pip-build-3xq5otjv\pycraft\


I used the command `pip install pyCraft`

**Comment by ammaraskar** [comment]
aah, the package on pip isn't actually us. It's by someone else https://pypi.python.org/pypi/PyCraft/1503040
It looks like its a word editing library. 

You want `pip install git+https://github.com/ammaraskar/pyCraft`

**Comment by friedkeenan** [comment]
Oh, weird. I ended up using the command `pip install https://github.com/ammaraskar/pyCraft/tarball/master' because I don't have git. Thanks for the help

**Comment by trenton3983** [comment]
Thank you.

**Comment by vizterror-commits** [comment]
how to download module minecraft
