### ISSUE TITLE
Is there a way to incorporate proxies into the connections?

### ISSUE THREAD

**Issue by kar731** [ammaraskar/pyCraft#66]

**Comment by joodicator** [comment]
What kind of proxy do you mean? If you mean TCP proxies like SOCKS, then the answer is that pyCraft does not currently support that; but it shouldn't be hard to add, and I'll consider doing so if you have a use for it.

**Comment by kar731** [comment]
Yeah, proxies like SOCKS or HTTP. This would be helpful for servers that limit 1 client per IP .

**Comment by joodicator** [comment]
Although I am sure there are legitimate uses for this feature, it does not sound like your intended use - bypassing a connection limit on a server - is one I would endorse, so I am not going to take the time add this feature myself, right now.
