### ISSUE TITLE
Working version/branch for each protocol version

### ISSUE THREAD

**Issue by remyroy** [ammaraskar/pyCraft#8]
Hello,

First, I would like to thank you for this wonderful application.

I need to connect to different servers with this client. Unfortunately, those servers are running different versions. It would be nice if you could have different branches or version of your code that would work with the different protocol versions while maintaining the same structure around it.

I wanted to try the version that is compatible with 1.2 but it did not seems to work properly with wx or something. I like the simplistic approach of using the command line you used in the latest version.

This is not an issue. I might try to implement it myself or get a simpler and working version that is compatible with 1.2.

**Comment by ammaraskar** [comment]
Now tagging versions
https://github.com/ammaraskar/pyCraft/releases
