### ISSUE TITLE
How to create your own scripts 

### ISSUE THREAD

**Issue by FruityCunt** [ammaraskar/pyCraft#85]
i am kinda new to python and i just a little confused how to add my own scripts to pycraft as i want to make player detectors plz help

**Comment by ammaraskar** [comment]
Hey, you definitely need a little bit of a background in terms of python programming to use pyCraft. Take a look at http://www.diveintopython3.net/ or https://wiki.python.org/moin/BeginnersGuide

Once you know the basics of running python scripts, you can start taking a look at the example code here: https://github.com/ammaraskar/pyCraft/blob/master/start.py

That file has an example of using the library in a command line application. Go down that road and come back here and ask any specific questions if you have any. Good luck :)
