### ISSUE TITLE
-s argument does not support IPv6 addresses

### ISSUE THREAD

**Issue by Foorack** [ammaraskar/pyCraft#86]
Should support the format: [ipv6-address]:port

**Comment by joodicator** [comment]
Thank you for the report. `start.py` has been changed in bca783115cad961db653f8d7206129c7205c5410 to support IPv6 addresses enclosed in square brackets.

Also, as it happens, pyCraft did not support connecting to IPv6 addresses at all, but this has been changed in commit 67344f2ceb3c36c0c8e5c977b9005a44d698fc91.
