### ISSUE TITLE
Parsing packets without active connection

### ISSUE THREAD

**Issue by Retsim** [ammaraskar/pyCraft#87]
Hi everyone,

Can I use pyCraft to parse already saved packets using a tool like:
https://github.com/barneygale/rex

In fact I'm looking to save some packets from a game session using a sniffer.
Rex is a good example, but maybe pyCraft itself.  I like the idea of rex because I can clear it to the maximum, then just doing raw dumps, very lightweight, without a bunch of classes I will never use.
Or maybe just a scapy one-liner to save dump needed packets traffic.

I want to be able to create a software that may use pyCraft to decode/parse those saved packets, with no connection to the server. 
For ex, to get x y z infos from a "player position & look" packet dump, without needing to instanciate the Connection object and proxying again the game to listen to fresh packets as _I already have it_ and just want to decode it fast and simple.

Can I currently achieve that ?
Thanks !

**Comment by ammaraskar** [comment]
It's possible, there's certain intricacies that you have to be aware of. Namely the fact that different ids correspond to different packets depending on what state you're in. 

If you know the state you're in, you can follow the code in the library here that parses the structure of the packet: https://github.com/ammaraskar/pyCraft/blob/master/minecraft/networking/connection.py#L498-L508

Also note that pyCraft doesn't implement all the packets possible in the protocol, its just ones that people have contributed for their own needs and ones required for a connection or very basic movement.

**Comment by joodicator** [comment]
It is possible to do this with pyCraft, but you do have to duplicate some of the logic that currently occurs in the Connection object, to keep track of state variables, such as the game state and whether compression is enabled, required to accurately decode packets.

I once wrote a Python script that takes as input a [Wireshark](https://www.wireshark.org/) TCP stream dump, in YAML format, of the conversation between a Minecraft client and server, and prints out details of all the packets sent back and forth. You can find the script [here](https://gist.github.com/joodicator/20391386937de06ad3db9c436bba777f). It requires pyCraft to be installed in the system (or the `minecraft` package present in the same directory) and encryption to be disabled. It was a quick hack, so you might not find it easy to read.

**Comment by joodicator** [comment]
I'm closing this issue for now. If you have further questions, feel free to post them here.
