### ISSUE TITLE
Python 3.3 no longer supported by testing infrastructure

### ISSUE THREAD

**Issue by joodicator** [ammaraskar/pyCraft#88]
See for example the output from [this job](https://travis-ci.org/ammaraskar/pyCraft/jobs/380036292#L506-L513):
```
Installing setuptools, pip, wheel...
  Complete output from command /home/travis/build/a....tox/py33/bin/python - setuptools pip wheel:
  DEPRECATION: Python 3.3 supported has been deprecated and support for it will be dropped in the future. Please upgrade your Python.
Looking in links: /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages, /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/virtualenv_support, /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/virtualenv_support
Collecting setuptools
Collecting pip
Collecting wheel
wheel requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 3.3.6
```

I think the solution is to remove Python 3.3 from the tox config and add Python 3.6, which is now stable, and similarly change the Python versions that pyCraft is declared to support. Unless there's some trick I don't know of, it doesn't seem feasible to carry on reliably supporting Python 3.3. I would be interested to hear your opinion on this, @ammaraskar.

**Comment by ammaraskar** [comment]
Agreed, 3.3 is EOL anyway https://devguide.python.org/#status-of-python-branches

**Comment by joodicator** [comment]
Very well. This change has been made in da46c4553d9412fe9616a209a3436957aa65495a.
